name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # Use the desired Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Build the MkDocs site
    - name: Build MkDocs site
      run: mkdocs build --config-file updates_website/mkdocs.yml --site-dir updates_website/site

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
